// AUTO-GENERATED by scripts/fetch-ticketmaster-brand.mjs — do not edit.
// Refreshed on each prebuild. Source: https://www.ticketmaster.com/
export const TM_BRAND = {
  title: 'Ticketmaster: Buy Verified Tickets for Concerts, Sports, Theater and Events',
  description:
    'Buy and sell tickets online for concerts, sports, theater, family and other events near you from Ticketmaster.',
  icon: 'https://uk.tmconst.com/rc-50ca3ad1/images/favicon.ico',
} as const;
